src/tongsuenlogistic/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path

from products.views import ProductListView, ProductDetailView

from .views import home_page,contact_page,about_page,email,change_lang_to_thai,change_lang_to_eng,change_lang_to_cn
urlpatterns = [
    path('', home_page,name="home"),
    path('about/', contact_page),
    path('contact/', contact_page),
    path('email/', email),
    path('th/', change_lang_to_thai,name="th"),
    path('en/', change_lang_to_eng,name="en"),
    path('cn/', change_lang_to_cn,name="cn"),
    path('product/', ProductListView.as_view()),
    path('product/<int:pk>', ProductDetailView.as_view()),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/products/models.py
import random
import os
from django.db import models

def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name,ext = os.path.splitext(base_name)
    return name,ext

def upload_image_path(instance,filename):
    print(instance)
    print(filename)
    new_filename = random.randint(1,383001020)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)

    return "products/{new_filename}/{final_filename}".format(
            new_filename=new_filename,
            final_filename=final_filename
            )

class Product(models.Model):
    title       = models.CharField(max_length=120)
    description = models.TextField()
    price       = models.DecimalField(decimal_places=2,max_digits=20,default=39.99)
    image       = models.FileField(upload_to=upload_image_path,null=True,blank=True)
    def __str__(self):
        return self.title

src/products/views.py
from django.http import Http404
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Product
# Create your views here.

class ProductListView(ListView):
    queryset = Product.objects.all()
    template_name = "products/list.html"

    def get_context_data(self,*args,**kwargs):
        context = super(ProductListView,self).get_context_data(*args,**kwargs)
        print(context)
        return context

    def get_object(self, *args, **kwargs):
        request = self.request
        pk = self.kwargs.get('pk')
        instance = Product.objects.get_bu_id(pk)
        if instance is None:
            raise Http("Product doesn't exist")
        return instance
class ProductDetailView(DetailView):
    queryset = Product.objects.all()
    template_name = "products/detail.html"
    def get_context_data(self,*args,**kwargs):
        context = super(ProductListView,self).get_context_data(*args,**kwargs)
        print(context)
        return context

    def get_object(self, *args, **kwargs):
        request = self.request
        pk = self.kwargs.get('pk')
        instance = Product.objects.get_bu_id(pk)
        if instance is None:
            raise Http("Product doesn't exist")
        return instance

src/tongsuenlogistic/views.py
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import render,redirect
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives,EmailMessage
from django.urls import reverse

def home_page(request):
    
    if request.session.get("lang")== 'TH':
        context = {
        "lang":"TH"
        }
    elif request.session.get("lang") == 'EN':
        context = {
        "lang":"EN"
        }
    elif request.session.get("lang") == 'CN':
        context = {
        "lang":"CN"
        }
    else:
        context = {
        "lang":"TH"
        }
    return render(request,"index.html",context)

def about_page(request):
    return render(request,"index.html",{})

def contact_page(request): 
    return render(request,"index.html",{})

def change_lang_to_thai(request):
    request.session['lang'] = 'TH'
    context = {
        "lang":"TH"
        }
    return render(request,"index.html",context)
    
def change_lang_to_eng(request):
    request.session['lang'] = 'EN'
    context = {
        "lang":"EN"
        }
    return render(request,"index.html",context)

def change_lang_to_cn(request):
    request.session['lang'] = 'CN'
    context = {
        "lang":"CN"
        }
    return render(request,"index.html",context)

def email(request): #contact@tongsuenlogistics.co.th
    rendered = render_to_string('email.html', { 'foo': 'bar' })
    msg = EmailMessage('subject', rendered, 'tongsuenDev@gmail.com', ['atp12112@gmail.com'])
    msg.content_subtype = "html"  # Main content is now text/html
    msg.send()
    return render(request,"index.html",{})

src/products/templates/products/detail.html
{{ object.title }} <br/>

{{ object.description }}

src/products/templates/products/list.html
{% for obj in product_list %}
{{ obj.title }} <br/>
{% endfor %}

src/templates/email.html
<!doctype html>
<html>
  <head>
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Simple Transactional Email</title>
    <style>
    /* -------------------------------------
        INLINED WITH htmlemail.io/inline
    ------------------------------------- */
    /* -------------------------------------
        RESPONSIVE AND MOBILE FRIENDLY STYLES
    ------------------------------------- */
    @media only screen and (max-width: 620px) {
      table[class=body] h1 {
        font-size: 28px !important;
        margin-bottom: 10px !important;
      }
      table[class=body] p,
            table[class=body] ul,
            table[class=body] ol,
            table[class=body] td,
            table[class=body] span,
            table[class=body] a {
        font-size: 16px !important;
      }
      table[class=body] .wrapper,
            table[class=body] .article {
        padding: 10px !important;
      }
      table[class=body] .content {
        padding: 0 !important;
      }
      table[class=body] .container {
        padding: 0 !important;
        width: 100% !important;
      }
      table[class=body] .main {
        border-left-width: 0 !important;
        border-radius: 0 !important;
        border-right-width: 0 !important;
      }
      table[class=body] .btn table {
        width: 100% !important;
      }
      table[class=body] .btn a {
        width: 100% !important;
      }
      table[class=body] .img-responsive {
        height: auto !important;
        max-width: 100% !important;
        width: auto !important;
      }
    }

    /* -------------------------------------
        PRESERVE THESE STYLES IN THE HEAD
    ------------------------------------- */
    @media all {
      .ExternalClass {
        width: 100%;
      }
      .ExternalClass,
            .ExternalClass p,
            .ExternalClass span,
            .ExternalClass font,
            .ExternalClass td,
            .ExternalClass div {
        line-height: 100%;
      }
      .apple-link a {
        color: inherit !important;
        font-family: inherit !important;
        font-size: inherit !important;
        font-weight: inherit !important;
        line-height: inherit !important;
        text-decoration: none !important;
      }
      .btn-primary table td:hover {
        background-color: #34495e !important;
      }
      .btn-primary a:hover {
        background-color: #34495e !important;
        border-color: #34495e !important;
      }
    }
    </style>
  </head>
  <body class="" style="background-color: #f6f6f6; font-family: sans-serif; -webkit-font-smoothing: antialiased; font-size: 14px; line-height: 1.4; margin: 0; padding: 0; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;">
    <table border="0" cellpadding="0" cellspacing="0" class="body" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background-color: #f6f6f6;">
      <tr>
        <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;">&nbsp;</td>
        <td class="container" style="font-family: sans-serif; font-size: 14px; vertical-align: top; display: block; Margin: 0 auto; max-width: 580px; padding: 10px; width: 580px;">
          <div class="content" style="box-sizing: border-box; display: block; Margin: 0 auto; max-width: 580px; padding: 10px;">

            <!-- START CENTERED WHITE CONTAINER -->
            <span class="preheader" style="color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; mso-hide: all; visibility: hidden; width: 0;">This is preheader text. Some clients will show this text as a preview.</span>
            <table class="main" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background: #ffffff; border-radius: 3px;">

              <!-- START MAIN CONTENT AREA -->
              <tr>
                <td class="wrapper" style="font-family: sans-serif; font-size: 14px; vertical-align: top; box-sizing: border-box; padding: 20px;">
                  <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;">
                    <tr>
                      <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;">
                        <p style="font-family: sans-serif; font-size: 24px; font-weight:600; margin: 0; Margin-bottom: 15px;">You have quote.</p>
                          
                          
                        <p style="font-family: sans-serif; font-size: 18px; font-weight: 600; margin: 0; Margin-bottom: 5px;">TYPE QUOTE:</p> <p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;">Warehouse</p>
                          
                        <p style="font-family: sans-serif; font-size: 18px; font-weight: 600; margin: 0; Margin-bottom: 5px;">NAME:</p> <p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;">Attaphon Eamsahard</p> 
                        
                        <p style="font-family: sans-serif; font-size: 18px; font-weight: 600; margin: 0; Margin-bottom: 5px;">COMPANY NAME:</p> <p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;">Tongsuen</p> 
                          
                        <p style="font-family: sans-serif; font-size: 18px; font-weight: 600; margin: 0; Margin-bottom: 5px;">EMAIL:</p> <p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;">attaphon@gmail.com</p> 
                          
                        <p style="font-family: sans-serif; font-size: 18px; font-weight: 600; margin: 0; Margin-bottom: 5px;">TEL:</p> <p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;">0909093315</p> 
                          
                        <p style="font-family: sans-serif; font-size: 18px; font-weight: 600; margin: 0; Margin-bottom: 5px;">TYPE PRODUCT:</p> <p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;">xxxxxxx</p> 
                          
                        <p style="font-family: sans-serif; font-size: 18px; font-weight: 600; margin: 0; Margin-bottom: 5px;">DIRECTION:</p> <p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;">xxxxxxx</p> 
                        
                        <p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;">This is a really simple email template. Its sole purpose is to get the recipient to click the button with no distractions.</p>
                        <p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;">Good luck! Hope it works.</p>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>

            <!-- END MAIN CONTENT AREA -->
            </table>

            <!-- START FOOTER -->
            <div class="footer" style="clear: both; Margin-top: 10px; text-align: center; width: 100%;">
              <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;">
                <tr>
                  <td class="content-block" style="font-family: sans-serif; vertical-align: top; padding-bottom: 10px; padding-top: 10px; font-size: 12px; color: #999999; text-align: center;">
                    <span class="apple-link" style="color: #999999; font-size: 12px; text-align: center;">Company Inc, 3 Abbey Road, San Francisco CA 94102</span>
                    <br> Don't like these emails? <a href="http://i.imgur.com/CScmqnj.gif" style="text-decoration: underline; color: #999999; font-size: 12px; text-align: center;">Unsubscribe</a>.
                  </td>
                </tr>
                <tr>
                  <td class="content-block powered-by" style="font-family: sans-serif; vertical-align: top; padding-bottom: 10px; padding-top: 10px; font-size: 12px; color: #999999; text-align: center;">
                    Powered by <a href="http://htmlemail.io" style="color: #999999; font-size: 12px; text-align: center; text-decoration: none;">HTMLemail</a>.
                  </td>
                </tr>
              </table>
            </div>
            <!-- END FOOTER -->

          <!-- END CENTERED WHITE CONTAINER -->
          </div>
        </td>
        <td style="font-family: sans-serif; font-size: 14px; vertical-align: top;">&nbsp;</td>
      </tr>
    </table>
  </body>
</html>